apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-0pgs
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-uipb-tenant/rhtap-demo-app/hacbs-test-project-0pgs@sha256:4d6e65975a6f837932744474fba44272c69775e3f41cbc460b7e3610ef5de140
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
